// Writes supabase/seed.sql from src/mocks so the database and mock mode hold the same
// demo data. Run with `npm run seed:sql` after changing anything in src/mocks.
import { writeFileSync } from 'node:fs'
import * as mocks from '../src/mocks/index.js'

function literal(value) {
  if (value === null || value === undefined) return 'null'
  if (typeof value === 'boolean' || typeof value === 'number') return String(value)
  if (Array.isArray(value)) return value.length ? `array[${value.map(literal).join(', ')}]::text[]` : `'{}'::text[]`
  return `'${String(value).replaceAll("'", "''")}'`
}

// Re-runnable: rows that already exist are left alone.
function inserts(table, rows) {
  if (!rows.length) return `-- ${table}: none\n`
  const columns = Object.keys(rows[0])
  const values = rows.map((row) => `  (${columns.map((c) => literal(row[c])).join(', ')})`).join(',\n')
  return `insert into ${table} (${columns.join(', ')}) values\n${values}\non conflict do nothing;\n`
}

// Order matters for foreign keys. Users are listed inviter-first in the mocks.
const sql = `-- Demo data for Ditto.
-- GENERATED by supabase/generate-seed.js from src/mocks — edit the mocks, then run
-- \`npm run seed:sql\`. Run this after schema.sql in the Supabase SQL editor.

${inserts('users', mocks.users)}
${inserts('invites', mocks.invites)}
${inserts('connections', mocks.connections)}
${inserts('events', mocks.events)}
${inserts('attendances', mocks.attendances)}
${inserts('messages', mocks.messages)}
${inserts('direct_messages', mocks.direct_messages)}
${inserts('ratings', mocks.ratings)}`

const out = new URL('./seed.sql', import.meta.url)
writeFileSync(out, sql)
console.log(`Wrote ${out.pathname}`)
